version: 2
jobs: 
  build:
    docker:
      - image: circleci/golang:1.14
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: techtestuser
          POSTGRES_DB: techtestdb
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -v
      - run: go test -v -race -cover ./...
workflows:
  version: 2
  build-workflow:
    jobs:
      - build